### ISSUE TITLE
Works in dev, no response from request when deployed

### ISSUE THREAD

**Issue by alexvinidiktov** [qooxdoo/incubator.qx.io.jsonrpc#10]
Hello,

I've created a minimal example that exhibits this problem.

https://github.com/vinidiktov/jsonrpc-app1

If you run `qx serve`, and launch the app, then open the console, you'll see that the request returns the result "echo baz", which is correct.

If you run the same app with `qx deploy`, and launch the app (I use the command python -m SimpleHTTPServer to serve the deployed version on locahost:8000), then open the console, you won't see any result or exception.

It seems that the request gets sent but then gets stuck and no response gets back.

Here's the function that gets executed at app launch:

```
async function foo() {
        const client = new qx.io.jsonrpc.Client("https://app.vocabilis.com/vocabilis/test/public_call/jsonrpc2");
        try {
            let result = await client.sendRequest("foo", ['echo']);
            console.log('foo result: ', result)
        } catch(e) {
            console.log('exception when sending foo request: ', JSON.stringify(e))
        }
    }
```

I'm using qooxdoo 1.0.0-beta-20201116-0651, and incubator.qx.io.jsonrpc v 1 on macOS Catalina.

**Comment by vinidiktov** [comment]
Issue is resolved by upgrading to v2 of incubator.qx.io.jsonrpc.
