### ISSUE TITLE
Client.js:99 Uncaught (in promise) TypeError: Cannot read property 'reverse' of null

### ISSUE THREAD

**Issue by vinidiktov** [qooxdoo/incubator.qx.io.jsonrpc#5]
I've installed the library and have added this snippet to a button's execute event listener.

When I press the button I get the error message saying 'Client.js:99 Uncaught (in promise) TypeError: Cannot read property 'reverse' of null'.

I have these installed on my macOS Catalina machine:

"@qooxdoo/framework": "^6.0.0-beta-20200904-1332",
 "@qooxdoo/compiler": "^1.0.0-beta-20200904-1332",
 "qooxdoo/incubator.qx.io.jsonrpc": "^1.0.0"

```
   button1.addListener("execute", function() {
        /* eslint no-alert: "off" */
        (async()=>{
          const client = new qx.io.jsonrpc.Client("http://localhost:8000/vocabilis/test/public_call/jsonrpc2");
          let result;
          try {
            result = await client.sendRequest("foo", ['echo']);
            console.log('result: ', result)
          } catch(e) {
            // handle exceptions
          }
        })();
      });
```

```
Client.js:99 Uncaught (in promise) TypeError: Cannot read property 'reverse' of null
    at wrapper.qx.io.jsonrpc.Client.constructor() (Client.js:99)
    at new wrapper (Class.js:1673)
    at _callee$ (Application.js:69)
    at tryCatch (polyfill.js:6517)
    at Generator.invoke [as _invoke] (polyfill.js:6746)
    at Generator.prototype.<computed> [as next] (polyfill.js:6569)
    at asyncGeneratorStep (Util.js:1)
    at _next (Util.js:1)
    at Util.js:1
    at new Promise (<anonymous>)
    at Util.js:1
    at wrapper.<anonymous> (Application.js:68)
    at Direct.js:136
    at Function.qx.event.Utils.then() [as then] (Utils.js:143)
    at Direct.js:135
    at Array.qx.lang.normalize.Array.forEach() [as forEach] (Array.js:127)
```

**Comment by cboulanger** [comment]
Hi, thanks for reporting. The error is thrown because no transport has been selected. Can you put `@use(qx.io.transport.Xhr)` in the doc comment of your class and report if that helps? I will put a more informative error message into the code.

**Comment by vinidiktov** [comment]
Hello, Christian,

`@use(qx.io.transport.Xhr)` didn't help, but `@use(qx.io.jsonrpc.transport.Http)` did.

Thanks for your help!

**Comment by cboulanger** [comment]
You're right - that's for v1.0.0, which you are using. In master, what will become the 2.0.0 version, the name changes to `qx.io.transport.Xhr` to reflect the undelying implementation. In v2, there will be an addtional HTTP transport based on the fetch Web API - that's why the name needs to be changed - XHR is not the only HTTP transport available.

**Comment by cboulanger** [comment]
More info is here: https://github.com/qooxdoo/incubator.qx.io.jsonrpc#qooxdoo-transport-agnostic-high-level-io-apis-json-rpc-graphql

Don't upgrade yet (there isn't a package for v2 anyways ATM), some more breaking changes might come (although I hope not). If you have any wishes (or contributions) for v2, let me know.
